# Site settings
title: Duskfall
description: "Dusk's digital garden with mini-essays on knowledge management, tech, and more!."

# Site owner info
owner: Duskfall
owner_nickname: Dusk

# Frontmatter defaults
defaults:
  - scope:
      path: ""  # Applies to all files
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: blog
      permalink: /blog/:title

exclude:
  - README.md

include:
  - _citations/
  - _pages/
  - _assets/

collections:
  pages:
    output: true
  citations:
    output: false

kramdown:
  footnote_link_text: "[%s]"