# Site settings
title: Duskfall
description: "Dusk's digital garden with mini-essays on knowledge management, tech, and more!"

# Site owner info
owner: Duskfall
owner_nickname: Dusk

defaults:
  - scope:
      path: "" # Applies to all files
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: blog
      permalink: /blog/:title

exclude:
  - README.md

include:
  - _citations/
  - _pages/
  - _assets/

collections:
  pages:
    output: true
  citations: # Just need this here so Jekyll will actually process files in this directory.
    output: false

kramdown:
  footnote_link_text: "[%s]" # Make inline footnotes closer to Wikipedia's style
  footnote_backlink: "↩︎" # switch to this symbol so it doesn't appear as an emoji on mobile